### ISSUE TITLE
How to solve this problem?

### ISSUE THREAD

**Issue by hzaumsq** [raphael-group/STARCH#3]
INFO:root:preprocess 12720 2425 (12720, 2425)
INFO:root:done preprocessing...
True
INFO:root:getting spot network...
INFO:root:initializing labels...
Traceback (most recent call last):
  File "run_STARCH.py", line 34, in <module>
    operator = STARCH(i,n_clusters=n_clusters,num_states=3,normal_spots=normal_spots,beta_spots = beta_spot,nthreads=nthreads,gene_mapping_file_name=gene_mapping_file_name)
  File "/beegfs/home/msq/St/CNV/STARCH-master/STARCH.py", line 133, in __init__
    self.initialize_labels()
  File "/beegfs/home/msq/St/CNV/STARCH-master/STARCH.py", line 478, in initialize_labels
    km = KMeans(n_clusters=self.n_clusters).fit(dat.T)
  File "/beegfs/home/msq/miniconda3/envs/python2/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 974, in fit
    return_n_iter=True)
  File "/beegfs/home/msq/miniconda3/envs/python2/lib/python2.7/site-packages/sklearn/cluster/k_means_.py", line 314, in k_means
    order=order, copy=copy_x)
  File "/beegfs/home/msq/miniconda3/envs/python2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 573, in check_array
    allow_nan=force_all_finite == 'allow-nan')
  File "/beegfs/home/msq/miniconda3/envs/python2/lib/python2.7/site-packages/sklearn/utils/validation.py", line 56, in _assert_all_finite
    raise ValueError(msg_err.format(type_err, X.dtype))
ValueError: Input contains NaN, infinity or a value too large for dtype('float64').

**Comment by hzaumsq** [comment]
I use the 10x spatial result
The coed : runSTARCH.py -i ../cnv/ -t 20 --output yy --n_clusters 3 --outdir ./test

**Comment by hzaumsq** [comment]
Also could you provide the more details explanation of results
