### ISSUE TITLE
AttributeError: 'STARCH' object has no attribute 'means'

### ISSUE THREAD

**Issue by hzongyao** [raphael-group/STARCH#4]
I use this code `python run_STARCH.py -i ./DATA --output DMG -t 10 -m hgTables_hg19.txt -c 3`
The 10X directory containing barcodes.tsv, features.tsv, matrix.mtx, and tissue_positions_list.csv
The outcome is as follow:

Traceback (most recent call last):
  File "run_STARCH.py", line 34, in <module>
    operator = STARCH(i,n_clusters=n_clusters,num_states=3,normal_spots=normal_spots,beta_spots = beta_spot,nthreads=nthreads,gene_mapping_file_name=gene_m_mapping_file_name)
  File "/mnt/raid/huangzongyao/workflow/STARCH/STARCH.py", line 141, in __init__
    logger.info('starting means: '+str(self.means))
AttributeError: 'STARCH' object has no attribute 'means'

**Comment by WandeRum** [comment]
I have the same issue.

**Comment by amasden** [comment]
Same issue as well.

**Comment by dkzhang777** [comment]
I am running into this issue too

**Comment by lucaskerr** [comment]
I also have the same issue; image attached. I tried some simple tweaks to both the run_Starch.py and Starch.py scripts but no luck on my end. Any advice?

<img width="1042" alt="Screen Shot 2021-09-25 at 9 56 41 PM" src="https://user-images.githubusercontent.com/74282957/134794256-7795c754-978a-429c-a049-49a717a7752e.png">

**Comment by braphael8** [comment]
Can you tell us the machine type and Python version that you are using?  We have seen this issue sporadically on some installations but not on others.

**Comment by lucaskerr** [comment]
Thanks for your reply! I'm on a 2019 Macbook Pro, Big Sur Version 11.6. Python version 3.8.8. Considering your comment, I just tried running the Starch scripts again on a 2018 PC running Windows 10, Python version 3.7, but I ran into the same error: 'STARCH' object has no attribute 'means'.

**Comment by huoyuying** [comment]
> I have the same issue.

Can you solve this problem now? I have the same issue !

**Comment by whitneyt1** [comment]
has anyone been able to solve this? When running this on 36 reactions with n_clusters= 1, 2, 3 it successfully runs on all reactions except one reaction repeatedly receives this error when n_clusters=1 

thank you!
